<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<ApplicationIcon>Assets\app.ico</ApplicationIcon>

		<!-- User will see xdPlayer.exe -->
		<AssemblyName>xdPlayer</AssemblyName>

		<!-- Name exe after assembly -->
		<TargetName>xdPlayer</TargetName>
	</PropertyGroup>

</Project>